  consul:
    image: gliderlabs/consul
    volumes:
      - /data
      - ./src/config:/config
    environment:
      DNS_RESOLVES: consul
      DNS_PORT: 8600
    expose:
      - "8300"
      - "8301"
      - "8301/udp"
      - "8302"
      - "8302/udp"
      - "8400"
      - "8500"
      - "8600"
      - "8600/udp"
    ports:
      - "8500:8500"
    command: agent -server -dev -ui -bootstrap -data-dir=/data -config-dir=/config